DROP SEQUENCE CONTENT_SEQ;
DROP SEQUENCE SERIES_SEQ;
DROP SEQUENCE PRODUCT_CO_SEQ;
DROP SEQUENCE TAG_SEQ;

DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_CO CASCADE CONSTRAINTS;
DROP TABLE SERIES CASCADE CONSTRAINTS;
DROP TABLE CONTENT CASCADE CONSTRAINTS;
DROP TABLE TAG CASCADE CONSTRAINTS;
DROP TABLE TAG_TO CASCADE CONSTRAINTS;
DROP TABLE SHOP CASCADE CONSTRAINTS;
DROP TABLE RATING CASCADE CONSTRAINTS;

-- 콘텐츠 ID용
CREATE SEQUENCE CONTENT_SEQ
START WITH 1 INCREMENT BY 1 NOCACHE;

-- 시리즈 ID용
CREATE SEQUENCE SERIES_SEQ
START WITH 1 INCREMENT BY 1 NOCACHE;

-- 제작사 ID용
CREATE SEQUENCE PRODUCT_CO_SEQ
START WITH 1 INCREMENT BY 1 NOCACHE;

-- 태그 코드용
CREATE SEQUENCE TAG_SEQ
START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE MEMBER(
	ID		VARCHAR(16)	NOT NULL,
	Password	VARCHAR(16)	NOT NULL,
	Name	VARCHAR(15)	NOT NULL,
	Address	VARCHAR(30),
	Sex		CHAR,
	Birthday	DATE,
	IsAdmin	CHAR	DEFAULT	'F',
	PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_CO(
	ProdcoID		INT			NOT NULL,
	Prodname		VARCHAR(100)	NOT NULL,
	ProdInfo		VARCHAR(1024),
	PRIMARY KEY (ProdcoID)
);

CREATE TABLE SERIES(
	SeriesID	INT			NOT NULL,
	SName	VARCHAR(100)	NOT NULL,
	PRIMARY KEY (SeriesID),
	UNIQUE (SName)
);

CREATE TABLE CONTENT(
	ContentID		INT			NOT NULL,
	Title			VARCHAR(100)	NOT NULL,
	ReleaseDate	DATE			NOT NULL,
	PID			INT			NOT NULL,
	SID			INT,
	PRIMARY KEY (ContentID),
	FOREIGN KEY (PID) REFERENCES PRODUCT_CO(ProdcoID),
	FOREIGN KEY (SID) REFERENCES SERIES(SeriesID)
);

CREATE TABLE TAG(
	TagCode	INT			NOT NULL,
	Category	VARCHAR(15)	NOT NULL,
	Tag		VARCHAR(30)	NOT NULL,
	PRIMARY KEY (TagCode)
);

CREATE TABLE TAG_TO(
	TCode	INT	NOT NULL,
	CID		INT	NOT NULL,
	PRIMARY KEY (TCode, CID),
	FOREIGN KEY (TCode) REFERENCES TAG(TagCode),
	FOREIGN KEY (CID) REFERENCES CONTENT(ContentID)
);

CREATE TABLE SHOP(
	MainURL	VARCHAR(50),
	SubURL	VARCHAR(200),
	CID		INT	NOT NULL,
	PRIMARY KEY (MainURL, SubURL),
	FOREIGN KEY (CID) REFERENCES CONTENT(ContentID)
);

CREATE TABLE RATING(
	MID			VARCHAR(16)	NOT NULL,
	CID			INT			NOT NULL,
	Rating		INT			NOT NULL,
	Comm		VARCHAR(1024),
	Likes			INT,
	PRIMARY KEY (MID, CID),
	FOREIGN KEY (MID) REFERENCES MEMBER(ID),
	FOREIGN KEY (CID) REFERENCES CONTENT(ContentID)
);

COMMIT;